name: Install dependencies for Android build
description: Contains all dependencies for Android build
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq > /dev/null && \
        sudo apt-get install -qq locales > /dev/null && \
        sudo apt-get install -qq --no-install-recommends \
            autoconf \
            build-essential \
            curl \
            file \
            git \
            gpg-agent \
            less \
            lib32stdc++6 \
            lib32z1 \
            lib32z1-dev \
            libc6-dev \
            libgmp-dev \
            libmpc-dev \
            libmpfr-dev \
            libxslt-dev \
            libxml2-dev \
            libunwind-dev \
            libgcc-9-dev \
            m4 \
            ncurses-dev \
            ocaml \
            openjdk-11-jdk \
            openssh-client \
            pkg-config \
            ruby-full \
            software-properties-common \
            tzdata \
            unzip \
            vim-tiny \
            wget \
            zip \
            zlib1g-dev
      shell: bash

    - name: ☕️ Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'gradle'
        
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r21d
        local-cache: true
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Add targets
      run: |
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android
        rustup target add aarch64-linux-android
      shell: bash
    
    - name: Debug library
      run: find /usr -name libgcc*
      shell: bash
