name: Install dependencies for Android build
description: Contains all dependencies for Android build
runs:
  using: "composite"
  steps:
    - name: ☕️ Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'gradle'

    - name: Setup Android SDK
      uses: amyu/setup-android@v3
      with:   
        cache-disabled: true
        sdk-version: '28'
        build-tools-version: '28.0.3'
        ndk-version: '22.1.7171670'
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Add targets
      run: |
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android
        rustup target add aarch64-linux-android
      shell: bash
