name: Install dependencies for Android build
description: Contains all dependencies for Android build
runs:
  using: "composite"
  steps:
    - name: ☕️ Install Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        cache: 'gradle'

    - name: Install android dependencies
      run: |
        bash .github/setup_android.sh
        echo 'ANDROID_HOME=$ANDROID_HOME'
        echo 'ANDROID_NDK_HOME=$ANDROID_NDK_HOME'
        echo 'PATH=$PATH'
        echo 'export ANDROID_HOME=$ANDROID_HOME' >> "$GITHUB_ENV"
        echo 'export ANDROID_NDK_HOME=$ANDROID_NDK_HOME' >> "$GITHUB_ENV"
        echo 'export PATH=$PATH' >> "$GITHUB_ENV"
      shell: bash
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Add targets
      run: |
        rustup target add armv7-linux-androideabi
        rustup target add i686-linux-android
        rustup target add x86_64-linux-android
        rustup target add aarch64-linux-android
      shell: bash
