name: Publish production version

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nova-wallet/build_tools:pr-5
      credentials:
        username: stepanLav
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Kotlin linter
        run: ./gradlew ktlint

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Publish to publick Maven
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
