name: Publish stage version

on:
  push:
    branches:
      - "develop"
  pull_request:

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 🔧 Install dependencies
        uses: ./.github/workflows/install/

      - name: Kotlin linter
        run: ./gradlew ktlint

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Publish to staging Maven
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeSonatypeStagingRepository
